name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt using Chocolatey
        run: |
          choco install qt5-default --confirm

      - name: Display Qt Installation Directory
        shell: powershell
        run: |
          $qtPath = (Get-ChildItem -Path "C:\Program Files (x86)\*" -Include "Qt" -Recurse | Select-Object -First 1).FullName
          Write-Host "Qt installation directory: $qtPath"

