name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-runner:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Find qmake.exe path
        id: find-qt-path
        shell: powershell
        run: |
          $qtPath = Get-ChildItem -Path "C:\Program Files (x86)\Android\android-sdk\emulator\lib64\qt" -Filter "qmake" -Recurse -File | Select-Object -First 1 -ExpandProperty FullName
          if ($qtPath) {
            echo "##[set-output name=qt-path;]$qtPath"
          } else {
            Write-Host "qmake.exe not found in the specified path."
          }

      - name: Use Qt installation path
        run: |
          echo "qmake.exe path is ${{ steps.find-qt-path.outputs.qt-path }}"
